# INF20: ¿Qué equipamientos ofrecen simultáneamente dos o más servicios públicos?

PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX edintinf: <https://edint.es/def/infraestructura#>
PREFIX edintkos: <https://edint.es/def/kos#>
PREFIX edintveh: <https://edint.es/def/censo-vehiculos#>
PREFIX esadm: <http://vocab.linkeddata.es/datosabiertos/def/sector-publico/territorio#>
PREFIX escjr: <http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/callejero#>
PREFIX esdir: <http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/direccion-postal#>
PREFIX fnml: <http://semweb.mmlab.be/ns/fnml#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX formats: <http://www.w3.org/ns/formats/>
PREFIX geo: <https://datos.ign.es/def/geo_core#>
PREFIX geosparql: <http://www.opengis.net/ont/geosparql#>
PREFIX grel: <http://users.ugent.be/~bjdmeest/function/grel.ttl#>
PREFIX gsp: <http://www.opengis.net/ont/geosparql#>
PREFIX mod: <https://w3id.org/mod#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX ql: <http://semweb.mmlab.be/ns/ql#>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX trafico: <http://vocab.ciudadesabiertas.es/def/transporte/trafico#>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?facility ?facilityLabel ?role
WHERE {
    ?facility a edintinf:Facility .
    OPTIONAL { ?facility rdfs:label ?facilityLabel }
    OPTIONAL { ?facility edintinf:hasManagementRoleType ?role }
}
ORDER BY ?facilityLabel

#==============================================================================
# VARIANTS (documentación)
#==============================================================================

# SELECT ?facility ?facilityLabel (COUNT(DISTINCT ?service) AS ?numServices)
# WHERE {
    # ?facility a edintinf:Facility ;
              # edintinf:providesPublicService ?service .

    # OPTIONAL { ?facility rdfs:label ?facilityLabel . }
# }
# GROUP BY ?facility ?facilityLabel
# HAVING (COUNT(DISTINCT ?service) >= 2)
# ORDER BY DESC(?numServices)


