# INF26: ¿Cuál es la localización de un elemento de movilidad concreto?

PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX edintinf: <https://edint.es/def/infraestructura#>
PREFIX edintkos: <https://edint.es/def/kos#>
PREFIX edintveh: <https://edint.es/def/censo-vehiculos#>
PREFIX esadm: <http://vocab.linkeddata.es/datosabiertos/def/sector-publico/territorio#>
PREFIX escjr: <http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/callejero#>
PREFIX esdir: <http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/direccion-postal#>
PREFIX fnml: <http://semweb.mmlab.be/ns/fnml#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX formats: <http://www.w3.org/ns/formats/>
PREFIX geo: <https://datos.ign.es/def/geo_core#>
PREFIX geosparql: <http://www.opengis.net/ont/geosparql#>
PREFIX grel: <http://users.ugent.be/~bjdmeest/function/grel.ttl#>
PREFIX gsp: <http://www.opengis.net/ont/geosparql#>
PREFIX mod: <https://w3id.org/mod#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX ql: <http://semweb.mmlab.be/ns/ql#>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX trafico: <http://vocab.ciudadesabiertas.es/def/transporte/trafico#>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?infra ?infraLabel ?owner ?ownerLabel
WHERE {
    ?infra a edintinf:Facility ;
           edintinf:registeredOwner ?owner .
    OPTIONAL { ?infra rdfs:label ?infraLabel }
    OPTIONAL { ?owner rdfs:label ?ownerLabel }
}
ORDER BY ?ownerLabel ?infraLabel

#==============================================================================
# VARIANTS (documentación)
#==============================================================================

# SELECT ?element ?elementLabel
       # ?geom
       # ?wkt
# WHERE {

    # Sustituye por la URI del elemento de movilidad
    # BIND(<URI-del-elemento> AS ?element)

    # OPTIONAL { ?element rdfs:label ?elementLabel . }

    # Geometría del elemento
    # ?element gsp:hasGeometry ?geom .

    # Representación geométrica en WKT
    # OPTIONAL { ?geom gsp:asWKT ?wkt . }
# }
