# Solo la lista de aparcamientos que cumplen (al menos una lectura)

PREFIX edintinf: <https://edint.es/def/infraestructura#>
PREFIX sosa:     <http://www.w3.org/ns/sosa/>
PREFIX rdfs:     <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:      <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?parking ?parkingLabel
WHERE {
  ?parking a edintinf:Parking ;
           edintinf:hasObservationPoint ?obsPoint .

  ?observation sosa:hasFeatureOfInterest ?obsPoint ;
               sosa:observedProperty edintinf:infrastructureOccupancy ;
               sosa:madeBySensor ?sensor ;
               sosa:resultTime ?time ;
               sosa:hasSimpleResult ?result .

  ?sensor a edintinf:CountingSensor .
  OPTIONAL { ?parking rdfs:label ?parkingLabel . }

    FILTER ( ?time >= "FECHA_INICIO_INTERVALO"^^xsd:dateTime &&
             ?time <= "FECHA_FIN_INTERVALO"^^xsd:dateTime )

  # Cambia la condición según necesites (=, >=, BETWEEN…)
  FILTER(xsd:decimal(?result) = 75)
}
ORDER BY ?parkingLabel
